// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNS5Nqhh_T9sA2bOVkEDdF_tzdXoODww',
    appId: '1:694870488169:web:9e0e6810195d50fbcb5ef8',
    messagingSenderId: '694870488169',
    projectId: 'vault-af031',
    authDomain: 'vault-af031.firebaseapp.com',
    storageBucket: 'vault-af031.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUprvv0N2Ehu3lKd69UtLSS7TA90sW7D4',
    appId: '1:694870488169:android:86ecfe774206be9dcb5ef8',
    messagingSenderId: '694870488169',
    projectId: 'vault-af031',
    storageBucket: 'vault-af031.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjHWny2n8XPBwmhPrlWxGe4MsvP1423Hk',
    appId: '1:694870488169:ios:5592ca2592f1b02dcb5ef8',
    messagingSenderId: '694870488169',
    projectId: 'vault-af031',
    storageBucket: 'vault-af031.firebasestorage.app',
    iosBundleId: 'com.anilguzel.vault',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjHWny2n8XPBwmhPrlWxGe4MsvP1423Hk',
    appId: '1:694870488169:ios:5592ca2592f1b02dcb5ef8',
    messagingSenderId: '694870488169',
    projectId: 'vault-af031',
    storageBucket: 'vault-af031.firebasestorage.app',
    iosBundleId: 'com.anilguzel.vault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvNS5Nqhh_T9sA2bOVkEDdF_tzdXoODww',
    appId: '1:694870488169:web:bb0b6725c4c3941dcb5ef8',
    messagingSenderId: '694870488169',
    projectId: 'vault-af031',
    authDomain: 'vault-af031.firebaseapp.com',
    storageBucket: 'vault-af031.firebasestorage.app',
  );
}
